apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
  namespace: rhacs-operator
status:
  conditions:
    - status: "True"
      type: Available
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector
  namespace: rhacs-operator
status:
  numberMisscheduled: 0
