kind: Secret
apiVersion: v1
metadata:
  name: acs-central-endpoint
  namespace: stackrox
data:
  UI: "<<insert ACSCS UI url here, encoded to BASE64 format>>"
  endpoint: "<< insert ACSCS endpoint URL here, encoded to BASE64 format>>"
type: Opaque
---
# Copy and paste your secrets init bundle below!
# And don't forget to add metadata -> namespace: stackrox
