kind: Secret
apiVersion: v1
metadata:
  name: acs-central-endpoint
  namespace: stackrox
data:
#insert your own urls here
  UI: aHR0cHM6Ly9hY3MtY2VjcTNzYmphNmRsNXM4NGJ0ODAuYWNzLnJoY2xvdWQuY29tCg==
  endpoint: YWNzLWRhdGEtY2VjcTNzYmphNmRsNXM4NGJ0ODAuYWNzLnJoY2xvdWQuY29tOjQ0Mw==
type: Opaque
---
# Copy and paste your secrets init bundle below!
# And don't forget to add metadata -> namespace: stackrox
