apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2023-02-15T16:17:43.535667109Z"
    init-bundle.stackrox.io/expires-at: "2024-02-15T16:18:00Z"
    init-bundle.stackrox.io/id: b9bf5a11-d689-40d5-bbb3-e4e27bcbf793
    init-bundle.stackrox.io/name: tmm-hub-cluster
  creationTimestamp: null
  name: sensor-tls
  namespace: rhacs-operator
data:
  sensor-cert.pem: '{{hub fromSecret "rhacs-operator" "sensor-tls" "sensor-cert.pem" hub}}'
  sensor-key.pem: '{{hub fromSecret "rhacs-operator" "sensor-tls" "sensor-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "rhacs-operator" "sensor-tls" "ca.pem" hub}}'
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2023-02-15T16:17:43.535667109Z"
    init-bundle.stackrox.io/expires-at: "2024-02-15T16:18:00Z"
    init-bundle.stackrox.io/id: b9bf5a11-d689-40d5-bbb3-e4e27bcbf793
    init-bundle.stackrox.io/name: tmm-hub-cluster
  creationTimestamp: null
  name: admission-control-tls
  namespace: rhacs-operator
data:
  admission-control-cert.pem: '{{hub fromSecret "rhacs-operator" "admission-control-tls" "admission-control-cert.pem" hub}}'
  admission-control-key.pem: '{{hub fromSecret "rhacs-operator" "admission-control-tls" "admission-control-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "rhacs-operator" "admission-control-tls" "ca.pem" hub}}'

---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2023-02-15T16:17:43.535667109Z"
    init-bundle.stackrox.io/expires-at: "2024-02-15T16:18:00Z"
    init-bundle.stackrox.io/id: b9bf5a11-d689-40d5-bbb3-e4e27bcbf793
    init-bundle.stackrox.io/name: tmm-hub-cluster
  creationTimestamp: null
  name: collector-tls
  namespace: rhacs-operator
data:
  collector-cert.pem: '{{hub fromSecret "rhacs-operator" "collector-tls" "collector-cert.pem" hub}}'
  collector-key.pem: '{{hub fromSecret "rhacs-operator" "collector-tls" "collector-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "rhacs-operator" "collector-tls" "ca.pem" hub}}'
